name: CLJS Tests

permissions:
  contents: read

on: [push]

jobs:
  # Runtime Tests
  runtime-test:
    name: Runtime Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - uses: DeLaGuardo/setup-clojure@13.2
        with:
          tools-deps: '1.12.0.1530'

      - name: Build tests
        run: clojure -M:cljs-test:adv

      - name: Run tests
        run: |
          node out-adv-node/tests.js | tee test-out.txt
          grep -qxF '0 failures, 0 errors.' test-out.txt
